Feature/drop 36/view onboarding medication reminders
jahorwitz/drops pull request #37
Opened 2024-11-05 00:20 UTC by CalebHasch

## Describe your changes
I created addMoreSection component that duplicates the passed element and used this in the medication reminders route to dynamically add and remove the reminders and medications.

## Issue ticket number and link
ticket#: 36
link: https://tripleten-apiary.atlassian.net/jira/software/projects/DROP/boards/5?selectedIssue=DROP-36

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-11-05 01:13 UTC, Aivaxela reviewed
Overall I think this is a very clean implementation! I left a couple of notes to maybe consider?
Also I'd be curious to see how well we'd actually be able to validate and submit all the form data here. I see you are using the useForm hook, so hopefully we can find a way to send those form values back to the submit function and on to the backend.

2024-11-05 01:13 UTC, Aivaxela commented on src/components/form/add-more-section.tsx
> +          ? React.cloneElement(children, { index, onDelete: removeChild, elementId: child })
nice use of React's cloneElement! this seems to be a good use-case for that function. the React docs do mention that this function can lead to "fragile code" but perhaps having the isValidElement check beforehand will help with this?

2024-11-05 01:13 UTC, Aivaxela commented on src/components/form/time-picker.tsx
> +          ></Button>
I think the plan - according to Josh - was to try and keep the trash button out of the time-picker element, to make sure each individual component as simple (and reusable) as possible. Maybe there is some way the trash icon can be added to the add-more-section?

2024-11-05 01:13 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-section.tsx
> +            />
again I wonder if the button can be part of the add-more-section somehow, to ensure all the control for managing the generic list is contained?

2024-11-05 01:13 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-time-input.tsx
> +                    }
same thing here, with the delete button

2024-11-05 01:13 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-section.tsx
> +  const inputName = `medication${elementId}` || "medication6"
a bit confused about the fallback to "medication6" but maybe I am missing something 😅

2024-11-05 01:13 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-reminder-form.tsx
> +        </Form.AddMoreSection>
the implementation looks very clean!

2024-11-06 23:33 UTC, Brian-J-Wang approved these changes
Looks good to me.

2024-11-07 21:46 UTC, Aivaxela requested changes
Nice work with the add-more section! I was able to integrate my step into it pretty easily. 
I left a few comments on some very minor, simple things to fix.

2024-11-07 21:46 UTC, Aivaxela commented on src/components/form/list-time-input.tsx
> +                  console.log(inputName)
leftover console.log statement? - probably needs deleted before moving to main

2024-11-07 21:46 UTC, Aivaxela commented on src/components/form/list-time-input.tsx
> +              onClick={() => {
might be a good idea to ensure the item isn't deleted if there is only 1 rendered (so the list is never empty) (if the user doesn't want reminders they'll just hit the skip button I believe)

2024-11-07 21:46 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-section.tsx
> +            <h3 className="font-text text-section-subtext font-normal leading-[24px] text-center">Medication {index}</h3>
looking at the Figma, this h3 should have a font-weight of 500 (tailwind class is `font-normal`)
also, the font size should be 24px (tailwind `text-2xl`)

2024-11-07 21:46 UTC, Aivaxela commented on src/routes/onboarding/set-medication-reminders/medication-reminder-form.tsx
> +      <h2 className="font-text text-section-header font-medium leader-[38.4px] text-center max-w-[358px] mx-auto">Set your medication reminders</h2>
small Tailwind class typo here - the line-height class should be `leading-[38.4px]` not `leader`

2024-11-08 00:54 UTC, Brian-J-Wang requested changes
Just a small detail that I noticed while reviewing Riley's PR.

2024-11-08 00:54 UTC, Brian-J-Wang commented on src/routes/onboarding/set-medication-reminders/medication-reminder-form.tsx
> +        <Form.AddMoreSection buttonText="+ Add another medication">
There is too much spacing between this button and the bottom medication section. The Figma doc says that there should be 20px between the two elements.

Your implementation
![image](https://github.com/user-attachments/assets/b73e3c8b-16c1-4a0f-8a45-7332e9c98806)

Figma Docs
![image](https://github.com/user-attachments/assets/5f9a33dc-c134-4e3d-bbbc-42cb4342205b)
![image](https://github.com/user-attachments/assets/407e7b4c-d39b-48fb-aaf1-9502f8078a8f)

2024-11-08 16:07 UTC, Brian-J-Wang approved these changes
Looks good to me.

2024-11-08 16:17 UTC, Aivaxela approved these changes

2024-11-14 17:56 UTC, jahorwitz approved these changes

2024-11-14 17:56 UTC, merged