Feature/drop 37/onboarding exercise goals
jahorwitz/drops pull request #39
Opened 2024-11-08 02:25 UTC by EEliason1

## Describe your changes
Create onboarding exercise goals form/feature. Additional commits and file changes are present due to merges. Add to home screen items aren't relevant to the scope of this feature and are being reviewed in a different request.

## Issue ticket number and link
Drop 37
https://tripleten-apiary.atlassian.net/jira/software/projects/DROP/boards/5?selectedIssue=DROP-37

## Checklist before requesting a review

- [ x ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ x ] I have made any necessary updates to Storybook to accompany these changes
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings

2024-11-08 15:06 UTC, CalebHasch requested changes
Other than the comments looks really good. Once you fix those it should be ready for final review.

2024-11-10 03:09 UTC, RPinkha reviewed
Some things that need fixing, looks good otherwise.

2024-11-10 03:09 UTC, RPinkha commented on src/routes/onboarding/set-exercise-goals/set-exercise-goals-form.tsx
> +      <h2 className="font-text text-section-header font-medium leader-[38.4px] text-center max-w-[358px] mx-auto">Set your exercise goals</h2>
Misspelling here. 
Line height class is leading, not leader, so it needs to be leading-[38.4px] (I would probably round it down to 38px too).

In addition, you are missing text-black to make the text #121212 like the figma requires.

2024-11-10 03:09 UTC, RPinkha commented on src/routes/onboarding/set-exercise-goals/set-exercise-goals-form.tsx
> +      <p className="font-text text-center max-w-[358px] mx-auto mt-4 mb-8">Doing some exercise can benefit your well-being a lot!</p>
Missing "leading-[19px] text-black"

2024-11-10 03:09 UTC, RPinkha commented on src/components/form/form.tsx
> +Form.ListTimeInput = ListTimeInput;
This can be reverted to how it was before

2024-11-14 18:08 UTC, jahorwitz approved these changes

2024-11-14 18:08 UTC, merged